esp_toml_version = 1.0

firmware_images_url = "https://docs.espressif.com/projects/arduino-esp32-wokwi-test/en/docs-embed/_static/binaries/libraries/ESP32/examples/GPIO/Blink"

# Apps that you support and for which the binaries are available to publish.
supported_apps = ["Blink"]

image.esp32 = "esp32/Blink.ino.merged.bin"
image.esp32-s3 = "esp32s3/Blink.ino.merged.bin"
